### PR TITLE
phpunit 9 was released

### PR DESCRIPTION
**Pull request by SignpostMarv**
https://mobile.twitter.com/s_bergmann/status/1225698301208432642

### CODE REVIEW

**Comment by localheinz** [comment]
@SignpostMarv 

Looks like the build failure is related to network issues - can you amend and push again to retrigger the builds?

**Comment by SignpostMarv** [comment]
@localheinz currently waiting for all the builds to fail/some to pass, don't want to exacerbate the network issues.

had the network issues this week at the dayjob, 'tis frustrating.

**Comment by SignpostMarv** [comment]
> can you amend and push again to retrigger the builds?

sat at the day job, wasn't sure how to trigger a force push from the web interface, so added 7bf7bec

**Comment by SignpostMarv** [comment]
@localheinz looks like it's failing on deps=high? https://travis-ci.org/psalm/phpunit-psalm-plugin/jobs/647274152#L372

> ERROR: ArgumentTypeCoercion - hooks/TestCaseHandler.php:376:67 - Argument 1 of Psalm\Type\Union::__construct expects non-empty-array<int, Psalm\Type\Atomic>, parent type list<Psalm\Type\Atomic> provided

**Comment by weirdan** [comment]
That's a valid complaint, unions should not be empty.

**Comment by SignpostMarv** [comment]
@weirdan just added bac311a to allow travis to isolate build failures caused solely by using vimeo/psalm:dev-master

**Comment by SignpostMarv** [comment]
@weirdan @localheinz the bac311a theory seems to be working as expected, would it be appropriate to add `allow_failures` for `DEPS="dev"` ?

**Comment by weirdan** [comment]
Dev failures isolation is fine, but note that even on 7.4-high the tests run with PHPUnit 7. There must be some other dependency preventing installation of newer PHPUnit versions (could be codeception or psalm-codeception module).

**Comment by SignpostMarv** [comment]
@weirdan 4330aea should (hopefully) alleviate that somewhat, but as `codeception/base` has been archived, it looks like the psalm-codeception module will need to be updated when a corresponding update has been made to codeception in general.

**Comment by SignpostMarv** [comment]
a54c65c fails due to connection issues between travis and google ¬_¬: https://travis-ci.org/psalm/phpunit-psalm-plugin/jobs/647324167?utm_medium=notification&utm_source=github_status

**Comment by SignpostMarv** [comment]
23c57a0 borrows the cache directive from vimeo/psalm to trigger a fresh build as I'm not presently able to force-push.

**Comment by SignpostMarv** [comment]
[oh ffs](https://travis-ci.org/psalm/phpunit-psalm-plugin/jobs/647335823?utm_medium=notification&utm_source=github_status)

**Comment by muglug** [comment]
Thanks, going to troubleshoot any issues upstream

**Comment by weirdan** [comment]
You want to bump `codeception-psalm-module` to 0.3 and `codeception` to 4.0. It'll allow PHPUnit 8 (but not 9, yet). PHPUnit 9 is not allowed  by codeception constraints yet, even though there's a corresponding bridge version already available.

**Pull request merged**
