### PR TITLE
Support variadics in test methods

### PR DESCRIPTION
**Pull request by weirdan**
Adds support for typechecking variadic parameters in test methods.

Refs #23

### CODE REVIEW

**Comment by weirdan** [comment]
@SignpostMarv see if this addresses (at least part of) the issues you reported in #23

**Comment by SignpostMarv** [comment]
Currently pulling apart some older type hinting, will get back to the variadics shortly hopefully.

**Comment by SignpostMarv** [comment]
yup, that looks like #23 is resolved :D

**Comment by SignpostMarv** [comment]
however, it looks like template tags are a different issue, not a related issue :s

**Comment by weirdan** [comment]
Please report it separately then.

**Comment by SignpostMarv** [comment]
nope, that looks solved too (this or earlier build maybe?)

**Pull request merged**
